export const MockedData = [
  {
    id: "48",
    ranking: 1,
    team_name: "Santos",
    total_score: 89,
    wins: 27,
    loses: 11,
    draws: 8,
    goals_scored: 103,
    goals_taken: 58,
    goals_balance: 45,
  },
  {
    id: "46",
    ranking: 2,
    team_name: "Atlético pr",
    total_score: 86,
    wins: 25,
    loses: 10,
    draws: 11,
    goals_scored: 93,
    goals_taken: 56,
    goals_balance: 37,
  },
  {
    id: "33",
    ranking: 3,
    team_name: "São paulo",
    total_score: 83,
    wins: 24,
    loses: 12,
    draws: 11,
    goals_scored: 78,
    goals_taken: 43,
    goals_balance: 35,
  },
  {
    id: "25",
    ranking: 4,
    team_name: "Palmeiras",
    total_score: 79,
    wins: 22,
    loses: 11,
    draws: 13,
    goals_scored: 72,
    goals_taken: 47,
    goals_balance: 25,
  },
  {
    id: "35",
    ranking: 5,
    team_name: "São caetano",
    total_score: 78,
    wins: 23,
    loses: 15,
    draws: 9,
    goals_scored: 65,
    goals_taken: 49,
    goals_balance: 16,
  },
  {
    id: "40",
    ranking: 6,
    team_name: "Corinthians",
    total_score: 74,
    wins: 20,
    loses: 12,
    draws: 14,
    goals_scored: 54,
    goals_taken: 54,
    goals_balance: 0,
  },
  {
    id: "34",
    ranking: 7,
    team_name: "Goiás",
    total_score: 72,
    wins: 21,
    loses: 16,
    draws: 9,
    goals_scored: 81,
    goals_taken: 68,
    goals_balance: 13,
  },
  {
    id: "44",
    ranking: 8,
    team_name: "Juventude",
    total_score: 70,
    wins: 20,
    loses: 16,
    draws: 10,
    goals_scored: 60,
    goals_taken: 66,
    goals_balance: -6,
  },
  {
    id: "26",
    ranking: 9,
    team_name: "Fluminense",
    total_score: 67,
    wins: 18,
    loses: 15,
    draws: 13,
    goals_scored: 65,
    goals_taken: 68,
    goals_balance: -3,
  },
  {
    id: "42",
    ranking: 10,
    team_name: "Internacional",
    total_score: 67,
    wins: 20,
    loses: 19,
    draws: 7,
    goals_scored: 65,
    goals_taken: 58,
    goals_balance: 7,
  },
  {
    id: "27",
    ranking: 11,
    team_name: "Ponte preta",
    total_score: 64,
    wins: 19,
    loses: 20,
    draws: 7,
    goals_scored: 43,
    goals_taken: 73,
    goals_balance: -30,
  },
  {
    id: "39",
    ranking: 12,
    team_name: "Figueirense",
    total_score: 63,
    wins: 17,
    loses: 17,
    draws: 12,
    goals_scored: 57,
    goals_taken: 59,
    goals_balance: -2,
  },
  {
    id: "29",
    ranking: 13,
    team_name: "Coritiba",
    total_score: 62,
    wins: 15,
    loses: 14,
    draws: 17,
    goals_scored: 53,
    goals_taken: 48,
    goals_balance: 5,
  },
  {
    id: "37",
    ranking: 14,
    team_name: "Cruzeiro",
    total_score: 56,
    wins: 16,
    loses: 22,
    draws: 8,
    goals_scored: 69,
    goals_taken: 81,
    goals_balance: -12,
  },
  {
    id: "43",
    ranking: 15,
    team_name: "Paysandu",
    total_score: 56,
    wins: 14,
    loses: 18,
    draws: 14,
    goals_scored: 56,
    goals_taken: 76,
    goals_balance: -20,
  },
  {
    id: "38",
    ranking: 16,
    team_name: "Flamengo",
    total_score: 54,
    wins: 13,
    loses: 18,
    draws: 15,
    goals_scored: 51,
    goals_taken: 53,
    goals_balance: -2,
  },
  {
    id: "41",
    ranking: 17,
    team_name: "Paraná",
    total_score: 54,
    wins: 15,
    loses: 22,
    draws: 9,
    goals_scored: 52,
    goals_taken: 73,
    goals_balance: -21,
  },
  {
    id: "47",
    ranking: 18,
    team_name: "Vasco",
    total_score: 54,
    wins: 14,
    loses: 20,
    draws: 12,
    goals_scored: 64,
    goals_taken: 68,
    goals_balance: -4,
  },
  {
    id: "36",
    ranking: 19,
    team_name: "Atlético mg",
    total_score: 53,
    wins: 12,
    loses: 17,
    draws: 17,
    goals_scored: 60,
    goals_taken: 66,
    goals_balance: -6,
  },
  {
    id: "45",
    ranking: 20,
    team_name: "Botafogo",
    total_score: 51,
    wins: 11,
    loses: 17,
    draws: 18,
    goals_scored: 62,
    goals_taken: 71,
    goals_balance: -9,
  },
  {
    id: "30",
    ranking: 21,
    team_name: "Criciúma",
    total_score: 50,
    wins: 13,
    loses: 22,
    draws: 11,
    goals_scored: 60,
    goals_taken: 77,
    goals_balance: -17,
  },
  {
    id: "32",
    ranking: 22,
    team_name: "Guarani",
    total_score: 49,
    wins: 11,
    loses: 19,
    draws: 16,
    goals_scored: 43,
    goals_taken: 55,
    goals_balance: -12,
  },
  {
    id: "28",
    ranking: 23,
    team_name: "Vitória",
    total_score: 48,
    wins: 13,
    loses: 24,
    draws: 9,
    goals_scored: 68,
    goals_taken: 87,
    goals_balance: -19,
  },
  {
    id: "31",
    ranking: 24,
    team_name: "Grêmio",
    total_score: 39,
    wins: 9,
    loses: 25,
    draws: 12,
    goals_scored: 60,
    goals_taken: 80,
    goals_balance: -20,
  },
];
