export const MockedRawData = {
  partidas: [
    {
      visitante: "Vitória",
      resultado: "vitoria_mandante",
      data_partida: "13/12/2003",
      pontuacao_geral_mandante: {
        gols_fora_casa: 30,
        empates_fora_casa: 5,
        total_jogos: 46,
        gols_casa: 55,
        jogos_fora_casa: 23,
        vitorias_casa: 13,
        derrotas_casa: 4,
        total_pontos: 65,
        empates_casa: 6,
        pontos_fora_casa: 20,
        total_gols_sofridos: 75,
        total_vitorias: 18,
        vitorias_fora_casa: 5,
        total_derrotas: 17,
        pontos_casa: 45,
        derrotas_fora_casa: 13,
        total_gols_marcados: 85,
        jogos_casa: 23,
        total_empates: 11,
      },
      placar_visitante: 0,
      hora_partida: "16h00",
      mandante: "Paraná",
      placar_mandante: 2,
      estadio: "Pinheirão",
      pontuacao_geral_visitante: {
        gols_fora_casa: 20,
        empates_fora_casa: 6,
        total_jogos: 46,
        gols_casa: 30,
        jogos_fora_casa: 23,
        vitorias_casa: 11,
        derrotas_casa: 7,
        total_pontos: 56,
        empates_casa: 5,
        pontos_fora_casa: 18,
        total_gols_sofridos: 64,
        total_vitorias: 15,
        vitorias_fora_casa: 4,
        total_derrotas: 20,
        pontos_casa: 38,
        derrotas_fora_casa: 13,
        total_gols_marcados: 50,
        jogos_casa: 23,
        total_empates: 11,
      },
    },
    {
      visitante: "Criciúma",
      resultado: "vitoria_mandante",
      data_partida: "13/12/2003",
      pontuacao_geral_mandante: {
        gols_fora_casa: 30,
        empates_fora_casa: 5,
        total_jogos: 46,
        gols_casa: 37,
        jogos_fora_casa: 23,
        vitorias_casa: 14,
        derrotas_casa: 4,
        total_pontos: 73,
        empates_casa: 5,
        pontos_fora_casa: 26,
        total_gols_sofridos: 58,
        total_vitorias: 21,
        vitorias_fora_casa: 7,
        total_derrotas: 15,
        pontos_casa: 47,
        derrotas_fora_casa: 11,
        total_gols_marcados: 67,
        jogos_casa: 23,
        total_empates: 10,
      },
      placar_visitante: 0,
      hora_partida: "16h00",
      mandante: "Coritiba",
      placar_mandante: 2,
      estadio: "Couto Pereira",
      pontuacao_geral_visitante: {
        gols_fora_casa: 21,
        empates_fora_casa: 6,
        total_jogos: 46,
        gols_casa: 36,
        jogos_fora_casa: 23,
        vitorias_casa: 14,
        derrotas_casa: 6,
        total_pontos: 60,
        empates_casa: 3,
        pontos_fora_casa: 15,
        total_gols_sofridos: 68,
        total_vitorias: 17,
        vitorias_fora_casa: 3,
        total_derrotas: 20,
        pontos_casa: 45,
        derrotas_fora_casa: 14,
        total_gols_marcados: 57,
        jogos_casa: 23,
        total_empates: 9,
      },
    },
    {
      visitante: "Goiás",
      resultado: "vitoria_mandante",
      data_partida: "13/12/2003",
      pontuacao_geral_mandante: {
        gols_fora_casa: 36,
        empates_fora_casa: 10,
        total_jogos: 46,
        gols_casa: 40,
        jogos_fora_casa: 23,
        vitorias_casa: 13,
        derrotas_casa: 5,
        total_pontos: 72,
        empates_casa: 5,
        pontos_fora_casa: 28,
        total_gols_sofridos: 62,
        total_vitorias: 19,
        vitorias_fora_casa: 6,
        total_derrotas: 12,
        pontos_casa: 44,
        derrotas_fora_casa: 7,
        total_gols_marcados: 76,
        jogos_casa: 23,
        total_empates: 15,
      },
      placar_visitante: 2,
      hora_partida: "16h00",
      mandante: "Atlético mg",
      placar_mandante: 3,
      estadio: "Ipatingão",
      pontuacao_geral_visitante: {
        gols_fora_casa: 31,
        empates_fora_casa: 4,
        total_jogos: 46,
        gols_casa: 47,
        jogos_fora_casa: 23,
        vitorias_casa: 12,
        derrotas_casa: 4,
        total_pontos: 65,
        empates_casa: 7,
        pontos_fora_casa: 22,
        total_gols_sofridos: 63,
        total_vitorias: 18,
        vitorias_fora_casa: 6,
        total_derrotas: 17,
        pontos_casa: 43,
        derrotas_fora_casa: 13,
        total_gols_marcados: 78,
        jogos_casa: 23,
        total_empates: 11,
      },
    },
    {
      visitante: "Guarani",
      resultado: "vitoria_mandante",
      data_partida: "13/12/2003",
      pontuacao_geral_mandante: {
        gols_fora_casa: 21,
        empates_fora_casa: 6,
        total_jogos: 46,
        gols_casa: 41,
        jogos_fora_casa: 23,
        vitorias_casa: 11,
        derrotas_casa: 4,
        total_pontos: 65,
        empates_casa: 8,
        pontos_fora_casa: 24,
        total_gols_sofridos: 54,
        total_vitorias: 17,
        vitorias_fora_casa: 6,
        total_derrotas: 15,
        pontos_casa: 41,
        derrotas_fora_casa: 11,
        total_gols_marcados: 62,
        jogos_casa: 23,
        total_empates: 14,
      },
      placar_visitante: 0,
      hora_partida: "16h00",
      mandante: "Figueirense",
      placar_mandante: 2,
      estadio: "Orlando Scarpelli",
      pontuacao_geral_visitante: {
        gols_fora_casa: 20,
        empates_fora_casa: 7,
        total_jogos: 46,
        gols_casa: 44,
        jogos_fora_casa: 23,
        vitorias_casa: 15,
        derrotas_casa: 5,
        total_pontos: 61,
        empates_casa: 3,
        pontos_fora_casa: 13,
        total_gols_sofridos: 72,
        total_vitorias: 17,
        vitorias_fora_casa: 2,
        total_derrotas: 19,
        pontos_casa: 48,
        derrotas_fora_casa: 14,
        total_gols_marcados: 64,
        jogos_casa: 23,
        total_empates: 10,
      },
    },
    {
      visitante: "Internacional",
      resultado: "vitoria_mandante",
      data_partida: "13/12/2003",
      pontuacao_geral_mandante: {
        gols_fora_casa: 15,
        empates_fora_casa: 9,
        total_jogos: 46,
        gols_casa: 38,
        jogos_fora_casa: 23,
        vitorias_casa: 15,
        derrotas_casa: 3,
        total_pontos: 71,
        empates_casa: 5,
        pontos_fora_casa: 21,
        total_gols_sofridos: 37,
        total_vitorias: 19,
        vitorias_fora_casa: 4,
        total_derrotas: 13,
        pontos_casa: 50,
        derrotas_fora_casa: 10,
        total_gols_marcados: 53,
        jogos_casa: 23,
        total_empates: 14,
      },
      placar_visitante: 0,
      hora_partida: "16h00",
      mandante: "São caetano",
      placar_mandante: 5,
      estadio: "Anacleto Campanella",
      pontuacao_geral_visitante: {
        gols_fora_casa: 27,
        empates_fora_casa: 3,
        total_jogos: 46,
        gols_casa: 32,
        jogos_fora_casa: 23,
        vitorias_casa: 13,
        derrotas_casa: 3,
        total_pontos: 70,
        empates_casa: 7,
        pontos_fora_casa: 24,
        total_gols_sofridos: 57,
        total_vitorias: 20,
        vitorias_fora_casa: 7,
        total_derrotas: 16,
        pontos_casa: 46,
        derrotas_fora_casa: 13,
        total_gols_marcados: 59,
        jogos_casa: 23,
        total_empates: 10,
      },
    },
    {
      visitante: "Corinthians",
      resultado: "vitoria_mandante",
      data_partida: "14/12/2003",
      pontuacao_geral_mandante: {
        gols_fora_casa: 21,
        empates_fora_casa: 5,
        total_jogos: 46,
        gols_casa: 33,
        jogos_fora_casa: 23,
        vitorias_casa: 10,
        derrotas_casa: 7,
        total_pontos: 50,
        empates_casa: 6,
        pontos_fora_casa: 14,
        total_gols_sofridos: 68,
        total_vitorias: 13,
        vitorias_fora_casa: 3,
        total_derrotas: 22,
        pontos_casa: 36,
        derrotas_fora_casa: 15,
        total_gols_marcados: 54,
        jogos_casa: 23,
        total_empates: 11,
      },
      placar_visitante: 0,
      hora_partida: "16h00",
      mandante: "Grêmio",
      placar_mandante: 3,
      estadio: "Olímpico",
      pontuacao_geral_visitante: {
        gols_fora_casa: 25,
        empates_fora_casa: 8,
        total_jogos: 46,
        gols_casa: 36,
        jogos_fora_casa: 23,
        vitorias_casa: 11,
        derrotas_casa: 8,
        total_pontos: 57,
        empates_casa: 4,
        pontos_fora_casa: 20,
        total_gols_sofridos: 63,
        total_vitorias: 15,
        vitorias_fora_casa: 4,
        total_derrotas: 19,
        pontos_casa: 37,
        derrotas_fora_casa: 11,
        total_gols_marcados: 61,
        jogos_casa: 23,
        total_empates: 12,
      },
    },
    {
      visitante: "Fortaleza",
      resultado: "vitoria_mandante",
      data_partida: "14/12/2003",
      pontuacao_geral_mandante: {
        gols_fora_casa: 26,
        empates_fora_casa: 8,
        total_jogos: 46,
        gols_casa: 37,
        jogos_fora_casa: 23,
        vitorias_casa: 7,
        derrotas_casa: 6,
        total_pontos: 51,
        empates_casa: 10,
        pontos_fora_casa: 20,
        total_gols_sofridos: 73,
        total_vitorias: 11,
        vitorias_fora_casa: 4,
        total_derrotas: 17,
        pontos_casa: 31,
        derrotas_fora_casa: 11,
        total_gols_marcados: 63,
        jogos_casa: 23,
        total_empates: 18,
      },
      placar_visitante: 0,
      hora_partida: "16h00",
      mandante: "Ponte preta",
      placar_mandante: 2,
      estadio: "Moisés Lucarelli",
      pontuacao_geral_visitante: {
        gols_fora_casa: 19,
        empates_fora_casa: 7,
        total_jogos: 46,
        gols_casa: 39,
        jogos_fora_casa: 23,
        vitorias_casa: 10,
        derrotas_casa: 7,
        total_pontos: 49,
        empates_casa: 6,
        pontos_fora_casa: 13,
        total_gols_sofridos: 74,
        total_vitorias: 12,
        vitorias_fora_casa: 2,
        total_derrotas: 21,
        pontos_casa: 36,
        derrotas_fora_casa: 14,
        total_gols_marcados: 58,
        jogos_casa: 23,
        total_empates: 13,
      },
    },
    {
      visitante: "Cruzeiro",
      resultado: "derrota_mandante",
      data_partida: "14/12/2003",
      pontuacao_geral_mandante: {
        gols_fora_casa: 19,
        empates_fora_casa: 4,
        total_jogos: 46,
        gols_casa: 40,
        jogos_fora_casa: 23,
        vitorias_casa: 11,
        derrotas_casa: 6,
        total_pontos: 46,
        empates_casa: 6,
        pontos_fora_casa: 7,
        total_gols_sofridos: 92,
        total_vitorias: 12,
        vitorias_fora_casa: 1,
        total_derrotas: 24,
        pontos_casa: 39,
        derrotas_fora_casa: 18,
        total_gols_marcados: 59,
        jogos_casa: 23,
        total_empates: 10,
      },
      placar_visitante: 7,
      hora_partida: "16h00",
      mandante: "Bahia",
      placar_mandante: 0,
      estadio: "Fonte Nova",
      pontuacao_geral_visitante: {
        gols_fora_casa: 41,
        empates_fora_casa: 2,
        total_jogos: 46,
        gols_casa: 61,
        jogos_fora_casa: 23,
        vitorias_casa: 17,
        derrotas_casa: 1,
        total_pontos: 100,
        empates_casa: 5,
        pontos_fora_casa: 44,
        total_gols_sofridos: 47,
        total_vitorias: 31,
        vitorias_fora_casa: 14,
        total_derrotas: 8,
        pontos_casa: 56,
        derrotas_fora_casa: 7,
        total_gols_marcados: 102,
        jogos_casa: 23,
        total_empates: 7,
      },
    },
    {
      visitante: "Juventude",
      resultado: "vitoria_mandante",
      data_partida: "14/12/2003",
      pontuacao_geral_mandante: {
        gols_fora_casa: 16,
        empates_fora_casa: 4,
        total_jogos: 46,
        gols_casa: 36,
        jogos_fora_casa: 23,
        vitorias_casa: 11,
        derrotas_casa: 5,
        total_pontos: 50,
        empates_casa: 7,
        pontos_fora_casa: 10,
        total_gols_sofridos: 77,
        total_vitorias: 13,
        vitorias_fora_casa: 2,
        total_derrotas: 22,
        pontos_casa: 40,
        derrotas_fora_casa: 17,
        total_gols_marcados: 52,
        jogos_casa: 23,
        total_empates: 11,
      },
      placar_visitante: 0,
      hora_partida: "16h00",
      mandante: "Fluminense",
      placar_mandante: 1,
      estadio: "Maracanã",
      pontuacao_geral_visitante: {
        gols_fora_casa: 19,
        empates_fora_casa: 4,
        total_jogos: 46,
        gols_casa: 36,
        jogos_fora_casa: 23,
        vitorias_casa: 9,
        derrotas_casa: 4,
        total_pontos: 50,
        empates_casa: 10,
        pontos_fora_casa: 13,
        total_gols_sofridos: 70,
        total_vitorias: 12,
        vitorias_fora_casa: 3,
        total_derrotas: 20,
        pontos_casa: 37,
        derrotas_fora_casa: 16,
        total_gols_marcados: 55,
        jogos_casa: 23,
        total_empates: 14,
      },
    },
    {
      visitante: "Atlético pr",
      resultado: "empate",
      data_partida: "14/12/2003",
      pontuacao_geral_mandante: {
        gols_fora_casa: 21,
        empates_fora_casa: 5,
        total_jogos: 46,
        gols_casa: 53,
        jogos_fora_casa: 23,
        vitorias_casa: 13,
        derrotas_casa: 3,
        total_pontos: 57,
        empates_casa: 7,
        pontos_fora_casa: 11,
        total_gols_sofridos: 77,
        total_vitorias: 15,
        vitorias_fora_casa: 2,
        total_derrotas: 19,
        pontos_casa: 46,
        derrotas_fora_casa: 16,
        total_gols_marcados: 74,
        jogos_casa: 23,
        total_empates: 12,
      },
      placar_visitante: 2,
      hora_partida: "16h00",
      mandante: "Paysandu",
      placar_mandante: 2,
      estadio: "Mangueirão",
      pontuacao_geral_visitante: {
        gols_fora_casa: 22,
        empates_fora_casa: 6,
        total_jogos: 46,
        gols_casa: 44,
        jogos_fora_casa: 23,
        vitorias_casa: 14,
        derrotas_casa: 5,
        total_pontos: 61,
        empates_casa: 4,
        pontos_fora_casa: 15,
        total_gols_sofridos: 72,
        total_vitorias: 17,
        vitorias_fora_casa: 3,
        total_derrotas: 19,
        pontos_casa: 46,
        derrotas_fora_casa: 14,
        total_gols_marcados: 66,
        jogos_casa: 23,
        total_empates: 10,
      },
    },
    {
      visitante: "Santos",
      resultado: "empate",
      data_partida: "14/12/2003",
      pontuacao_geral_mandante: {
        gols_fora_casa: 25,
        empates_fora_casa: 8,
        total_jogos: 46,
        gols_casa: 32,
        jogos_fora_casa: 23,
        vitorias_casa: 11,
        derrotas_casa: 5,
        total_pontos: 54,
        empates_casa: 7,
        pontos_fora_casa: 14,
        total_gols_sofridos: 69,
        total_vitorias: 13,
        vitorias_fora_casa: 2,
        total_derrotas: 18,
        pontos_casa: 40,
        derrotas_fora_casa: 13,
        total_gols_marcados: 57,
        jogos_casa: 23,
        total_empates: 15,
      },
      placar_visitante: 1,
      hora_partida: "18h00",
      mandante: "Vasco",
      placar_mandante: 1,
      estadio: "São Januário",
      pontuacao_geral_visitante: {
        gols_fora_casa: 38,
        empates_fora_casa: 6,
        total_jogos: 46,
        gols_casa: 55,
        jogos_fora_casa: 23,
        vitorias_casa: 15,
        derrotas_casa: 2,
        total_pontos: 87,
        empates_casa: 6,
        pontos_fora_casa: 36,
        total_gols_sofridos: 60,
        total_vitorias: 25,
        vitorias_fora_casa: 10,
        total_derrotas: 9,
        pontos_casa: 51,
        derrotas_fora_casa: 7,
        total_gols_marcados: 93,
        jogos_casa: 23,
        total_empates: 12,
      },
    },
    {
      visitante: "Flamengo",
      resultado: "derrota_mandante",
      data_partida: "14/12/2003",
      pontuacao_geral_mandante: {
        gols_fora_casa: 39,
        empates_fora_casa: 7,
        total_jogos: 46,
        gols_casa: 42,
        jogos_fora_casa: 23,
        vitorias_casa: 13,
        derrotas_casa: 5,
        total_pontos: 78,
        empates_casa: 5,
        pontos_fora_casa: 34,
        total_gols_sofridos: 67,
        total_vitorias: 22,
        vitorias_fora_casa: 9,
        total_derrotas: 12,
        pontos_casa: 44,
        derrotas_fora_casa: 7,
        total_gols_marcados: 81,
        jogos_casa: 23,
        total_empates: 12,
      },
      placar_visitante: 3,
      hora_partida: "18h00",
      mandante: "São paulo",
      placar_mandante: 1,
      estadio: "Morumbi",
      pontuacao_geral_visitante: {
        gols_fora_casa: 28,
        empates_fora_casa: 7,
        total_jogos: 46,
        gols_casa: 38,
        jogos_fora_casa: 23,
        vitorias_casa: 14,
        derrotas_casa: 4,
        total_pontos: 66,
        empates_casa: 5,
        pontos_fora_casa: 19,
        total_gols_sofridos: 73,
        total_vitorias: 18,
        vitorias_fora_casa: 4,
        total_derrotas: 16,
        pontos_casa: 47,
        derrotas_fora_casa: 12,
        total_gols_marcados: 66,
        jogos_casa: 23,
        total_empates: 12,
      },
    },
  ],
  numero: 46,
};

export const MockedData = [
  {
    id: "48",
    ranking: 1,
    team_name: "Santos",
    total_score: 89,
    wins: 27,
    loses: 11,
    draws: 8,
    goals_scored: 103,
    goals_taken: 58,
    goals_balance: 45,
  },
  {
    id: "46",
    ranking: 2,
    team_name: "Atlético pr",
    total_score: 86,
    wins: 25,
    loses: 10,
    draws: 11,
    goals_scored: 93,
    goals_taken: 56,
    goals_balance: 37,
  },
  {
    id: "33",
    ranking: 3,
    team_name: "São paulo",
    total_score: 83,
    wins: 24,
    loses: 12,
    draws: 11,
    goals_scored: 78,
    goals_taken: 43,
    goals_balance: 35,
  },
  {
    id: "25",
    ranking: 4,
    team_name: "Palmeiras",
    total_score: 79,
    wins: 22,
    loses: 11,
    draws: 13,
    goals_scored: 72,
    goals_taken: 47,
    goals_balance: 25,
  },
  {
    id: "35",
    ranking: 5,
    team_name: "São caetano",
    total_score: 78,
    wins: 23,
    loses: 15,
    draws: 9,
    goals_scored: 65,
    goals_taken: 49,
    goals_balance: 16,
  },
  {
    id: "40",
    ranking: 6,
    team_name: "Corinthians",
    total_score: 74,
    wins: 20,
    loses: 12,
    draws: 14,
    goals_scored: 54,
    goals_taken: 54,
    goals_balance: 0,
  },
  {
    id: "34",
    ranking: 7,
    team_name: "Goiás",
    total_score: 72,
    wins: 21,
    loses: 16,
    draws: 9,
    goals_scored: 81,
    goals_taken: 68,
    goals_balance: 13,
  },
  {
    id: "44",
    ranking: 8,
    team_name: "Juventude",
    total_score: 70,
    wins: 20,
    loses: 16,
    draws: 10,
    goals_scored: 60,
    goals_taken: 66,
    goals_balance: -6,
  },
  {
    id: "26",
    ranking: 9,
    team_name: "Fluminense",
    total_score: 67,
    wins: 18,
    loses: 15,
    draws: 13,
    goals_scored: 65,
    goals_taken: 68,
    goals_balance: -3,
  },
  {
    id: "42",
    ranking: 10,
    team_name: "Internacional",
    total_score: 67,
    wins: 20,
    loses: 19,
    draws: 7,
    goals_scored: 65,
    goals_taken: 58,
    goals_balance: 7,
  },
  {
    id: "27",
    ranking: 11,
    team_name: "Ponte preta",
    total_score: 64,
    wins: 19,
    loses: 20,
    draws: 7,
    goals_scored: 43,
    goals_taken: 73,
    goals_balance: -30,
  },
  {
    id: "39",
    ranking: 12,
    team_name: "Figueirense",
    total_score: 63,
    wins: 17,
    loses: 17,
    draws: 12,
    goals_scored: 57,
    goals_taken: 59,
    goals_balance: -2,
  },
  {
    id: "29",
    ranking: 13,
    team_name: "Coritiba",
    total_score: 62,
    wins: 15,
    loses: 14,
    draws: 17,
    goals_scored: 53,
    goals_taken: 48,
    goals_balance: 5,
  },
  {
    id: "37",
    ranking: 14,
    team_name: "Cruzeiro",
    total_score: 56,
    wins: 16,
    loses: 22,
    draws: 8,
    goals_scored: 69,
    goals_taken: 81,
    goals_balance: -12,
  },
  {
    id: "43",
    ranking: 15,
    team_name: "Paysandu",
    total_score: 56,
    wins: 14,
    loses: 18,
    draws: 14,
    goals_scored: 56,
    goals_taken: 76,
    goals_balance: -20,
  },
  {
    id: "38",
    ranking: 16,
    team_name: "Flamengo",
    total_score: 54,
    wins: 13,
    loses: 18,
    draws: 15,
    goals_scored: 51,
    goals_taken: 53,
    goals_balance: -2,
  },
  {
    id: "41",
    ranking: 17,
    team_name: "Paraná",
    total_score: 54,
    wins: 15,
    loses: 22,
    draws: 9,
    goals_scored: 52,
    goals_taken: 73,
    goals_balance: -21,
  },
  {
    id: "47",
    ranking: 18,
    team_name: "Vasco",
    total_score: 54,
    wins: 14,
    loses: 20,
    draws: 12,
    goals_scored: 64,
    goals_taken: 68,
    goals_balance: -4,
  },
  {
    id: "36",
    ranking: 19,
    team_name: "Atlético mg",
    total_score: 53,
    wins: 12,
    loses: 17,
    draws: 17,
    goals_scored: 60,
    goals_taken: 66,
    goals_balance: -6,
  },
  {
    id: "45",
    ranking: 20,
    team_name: "Botafogo",
    total_score: 51,
    wins: 11,
    loses: 17,
    draws: 18,
    goals_scored: 62,
    goals_taken: 71,
    goals_balance: -9,
  },
  {
    id: "30",
    ranking: 21,
    team_name: "Criciúma",
    total_score: 50,
    wins: 13,
    loses: 22,
    draws: 11,
    goals_scored: 60,
    goals_taken: 77,
    goals_balance: -17,
  },
  {
    id: "32",
    ranking: 22,
    team_name: "Guarani",
    total_score: 49,
    wins: 11,
    loses: 19,
    draws: 16,
    goals_scored: 43,
    goals_taken: 55,
    goals_balance: -12,
  },
  {
    id: "28",
    ranking: 23,
    team_name: "Vitória",
    total_score: 48,
    wins: 13,
    loses: 24,
    draws: 9,
    goals_scored: 68,
    goals_taken: 87,
    goals_balance: -19,
  },
  {
    id: "31",
    ranking: 24,
    team_name: "Grêmio",
    total_score: 39,
    wins: 9,
    loses: 25,
    draws: 12,
    goals_scored: 60,
    goals_taken: 80,
    goals_balance: -20,
  },
];

export const MockedRawDataList = [
  {
    partidas: [
      {
        visitante: "Vitória",
        resultado: "vitoria_mandante",
        data_partida: "13/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 30,
          empates_fora_casa: 5,
          total_jogos: 46,
          gols_casa: 55,
          jogos_fora_casa: 23,
          vitorias_casa: 13,
          derrotas_casa: 4,
          total_pontos: 65,
          empates_casa: 6,
          pontos_fora_casa: 20,
          total_gols_sofridos: 75,
          total_vitorias: 18,
          vitorias_fora_casa: 5,
          total_derrotas: 17,
          pontos_casa: 45,
          derrotas_fora_casa: 13,
          total_gols_marcados: 85,
          jogos_casa: 23,
          total_empates: 11,
        },
        placar_visitante: 0,
        hora_partida: "16h00",
        mandante: "Paraná",
        placar_mandante: 2,
        estadio: "Pinheirão",
        pontuacao_geral_visitante: {
          gols_fora_casa: 20,
          empates_fora_casa: 6,
          total_jogos: 46,
          gols_casa: 30,
          jogos_fora_casa: 23,
          vitorias_casa: 11,
          derrotas_casa: 7,
          total_pontos: 56,
          empates_casa: 5,
          pontos_fora_casa: 18,
          total_gols_sofridos: 64,
          total_vitorias: 15,
          vitorias_fora_casa: 4,
          total_derrotas: 20,
          pontos_casa: 38,
          derrotas_fora_casa: 13,
          total_gols_marcados: 50,
          jogos_casa: 23,
          total_empates: 11,
        },
      },
      {
        visitante: "Criciúma",
        resultado: "vitoria_mandante",
        data_partida: "13/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 30,
          empates_fora_casa: 5,
          total_jogos: 46,
          gols_casa: 37,
          jogos_fora_casa: 23,
          vitorias_casa: 14,
          derrotas_casa: 4,
          total_pontos: 73,
          empates_casa: 5,
          pontos_fora_casa: 26,
          total_gols_sofridos: 58,
          total_vitorias: 21,
          vitorias_fora_casa: 7,
          total_derrotas: 15,
          pontos_casa: 47,
          derrotas_fora_casa: 11,
          total_gols_marcados: 67,
          jogos_casa: 23,
          total_empates: 10,
        },
        placar_visitante: 0,
        hora_partida: "16h00",
        mandante: "Coritiba",
        placar_mandante: 2,
        estadio: "Couto Pereira",
        pontuacao_geral_visitante: {
          gols_fora_casa: 21,
          empates_fora_casa: 6,
          total_jogos: 46,
          gols_casa: 36,
          jogos_fora_casa: 23,
          vitorias_casa: 14,
          derrotas_casa: 6,
          total_pontos: 60,
          empates_casa: 3,
          pontos_fora_casa: 15,
          total_gols_sofridos: 68,
          total_vitorias: 17,
          vitorias_fora_casa: 3,
          total_derrotas: 20,
          pontos_casa: 45,
          derrotas_fora_casa: 14,
          total_gols_marcados: 57,
          jogos_casa: 23,
          total_empates: 9,
        },
      },
      {
        visitante: "Goiás",
        resultado: "vitoria_mandante",
        data_partida: "13/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 36,
          empates_fora_casa: 10,
          total_jogos: 46,
          gols_casa: 40,
          jogos_fora_casa: 23,
          vitorias_casa: 13,
          derrotas_casa: 5,
          total_pontos: 72,
          empates_casa: 5,
          pontos_fora_casa: 28,
          total_gols_sofridos: 62,
          total_vitorias: 19,
          vitorias_fora_casa: 6,
          total_derrotas: 12,
          pontos_casa: 44,
          derrotas_fora_casa: 7,
          total_gols_marcados: 76,
          jogos_casa: 23,
          total_empates: 15,
        },
        placar_visitante: 2,
        hora_partida: "16h00",
        mandante: "Atlético mg",
        placar_mandante: 3,
        estadio: "Ipatingão",
        pontuacao_geral_visitante: {
          gols_fora_casa: 31,
          empates_fora_casa: 4,
          total_jogos: 46,
          gols_casa: 47,
          jogos_fora_casa: 23,
          vitorias_casa: 12,
          derrotas_casa: 4,
          total_pontos: 65,
          empates_casa: 7,
          pontos_fora_casa: 22,
          total_gols_sofridos: 63,
          total_vitorias: 18,
          vitorias_fora_casa: 6,
          total_derrotas: 17,
          pontos_casa: 43,
          derrotas_fora_casa: 13,
          total_gols_marcados: 78,
          jogos_casa: 23,
          total_empates: 11,
        },
      },
      {
        visitante: "Guarani",
        resultado: "vitoria_mandante",
        data_partida: "13/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 21,
          empates_fora_casa: 6,
          total_jogos: 46,
          gols_casa: 41,
          jogos_fora_casa: 23,
          vitorias_casa: 11,
          derrotas_casa: 4,
          total_pontos: 65,
          empates_casa: 8,
          pontos_fora_casa: 24,
          total_gols_sofridos: 54,
          total_vitorias: 17,
          vitorias_fora_casa: 6,
          total_derrotas: 15,
          pontos_casa: 41,
          derrotas_fora_casa: 11,
          total_gols_marcados: 62,
          jogos_casa: 23,
          total_empates: 14,
        },
        placar_visitante: 0,
        hora_partida: "16h00",
        mandante: "Figueirense",
        placar_mandante: 2,
        estadio: "Orlando Scarpelli",
        pontuacao_geral_visitante: {
          gols_fora_casa: 20,
          empates_fora_casa: 7,
          total_jogos: 46,
          gols_casa: 44,
          jogos_fora_casa: 23,
          vitorias_casa: 15,
          derrotas_casa: 5,
          total_pontos: 61,
          empates_casa: 3,
          pontos_fora_casa: 13,
          total_gols_sofridos: 72,
          total_vitorias: 17,
          vitorias_fora_casa: 2,
          total_derrotas: 19,
          pontos_casa: 48,
          derrotas_fora_casa: 14,
          total_gols_marcados: 64,
          jogos_casa: 23,
          total_empates: 10,
        },
      },
      {
        visitante: "Internacional",
        resultado: "vitoria_mandante",
        data_partida: "13/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 15,
          empates_fora_casa: 9,
          total_jogos: 46,
          gols_casa: 38,
          jogos_fora_casa: 23,
          vitorias_casa: 15,
          derrotas_casa: 3,
          total_pontos: 71,
          empates_casa: 5,
          pontos_fora_casa: 21,
          total_gols_sofridos: 37,
          total_vitorias: 19,
          vitorias_fora_casa: 4,
          total_derrotas: 13,
          pontos_casa: 50,
          derrotas_fora_casa: 10,
          total_gols_marcados: 53,
          jogos_casa: 23,
          total_empates: 14,
        },
        placar_visitante: 0,
        hora_partida: "16h00",
        mandante: "São caetano",
        placar_mandante: 5,
        estadio: "Anacleto Campanella",
        pontuacao_geral_visitante: {
          gols_fora_casa: 27,
          empates_fora_casa: 3,
          total_jogos: 46,
          gols_casa: 32,
          jogos_fora_casa: 23,
          vitorias_casa: 13,
          derrotas_casa: 3,
          total_pontos: 70,
          empates_casa: 7,
          pontos_fora_casa: 24,
          total_gols_sofridos: 57,
          total_vitorias: 20,
          vitorias_fora_casa: 7,
          total_derrotas: 16,
          pontos_casa: 46,
          derrotas_fora_casa: 13,
          total_gols_marcados: 59,
          jogos_casa: 23,
          total_empates: 10,
        },
      },
      {
        visitante: "Corinthians",
        resultado: "vitoria_mandante",
        data_partida: "14/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 21,
          empates_fora_casa: 5,
          total_jogos: 46,
          gols_casa: 33,
          jogos_fora_casa: 23,
          vitorias_casa: 10,
          derrotas_casa: 7,
          total_pontos: 50,
          empates_casa: 6,
          pontos_fora_casa: 14,
          total_gols_sofridos: 68,
          total_vitorias: 13,
          vitorias_fora_casa: 3,
          total_derrotas: 22,
          pontos_casa: 36,
          derrotas_fora_casa: 15,
          total_gols_marcados: 54,
          jogos_casa: 23,
          total_empates: 11,
        },
        placar_visitante: 0,
        hora_partida: "16h00",
        mandante: "Grêmio",
        placar_mandante: 3,
        estadio: "Olímpico",
        pontuacao_geral_visitante: {
          gols_fora_casa: 25,
          empates_fora_casa: 8,
          total_jogos: 46,
          gols_casa: 36,
          jogos_fora_casa: 23,
          vitorias_casa: 11,
          derrotas_casa: 8,
          total_pontos: 57,
          empates_casa: 4,
          pontos_fora_casa: 20,
          total_gols_sofridos: 63,
          total_vitorias: 15,
          vitorias_fora_casa: 4,
          total_derrotas: 19,
          pontos_casa: 37,
          derrotas_fora_casa: 11,
          total_gols_marcados: 61,
          jogos_casa: 23,
          total_empates: 12,
        },
      },
      {
        visitante: "Fortaleza",
        resultado: "vitoria_mandante",
        data_partida: "14/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 26,
          empates_fora_casa: 8,
          total_jogos: 46,
          gols_casa: 37,
          jogos_fora_casa: 23,
          vitorias_casa: 7,
          derrotas_casa: 6,
          total_pontos: 51,
          empates_casa: 10,
          pontos_fora_casa: 20,
          total_gols_sofridos: 73,
          total_vitorias: 11,
          vitorias_fora_casa: 4,
          total_derrotas: 17,
          pontos_casa: 31,
          derrotas_fora_casa: 11,
          total_gols_marcados: 63,
          jogos_casa: 23,
          total_empates: 18,
        },
        placar_visitante: 0,
        hora_partida: "16h00",
        mandante: "Ponte preta",
        placar_mandante: 2,
        estadio: "Moisés Lucarelli",
        pontuacao_geral_visitante: {
          gols_fora_casa: 19,
          empates_fora_casa: 7,
          total_jogos: 46,
          gols_casa: 39,
          jogos_fora_casa: 23,
          vitorias_casa: 10,
          derrotas_casa: 7,
          total_pontos: 49,
          empates_casa: 6,
          pontos_fora_casa: 13,
          total_gols_sofridos: 74,
          total_vitorias: 12,
          vitorias_fora_casa: 2,
          total_derrotas: 21,
          pontos_casa: 36,
          derrotas_fora_casa: 14,
          total_gols_marcados: 58,
          jogos_casa: 23,
          total_empates: 13,
        },
      },
      {
        visitante: "Cruzeiro",
        resultado: "derrota_mandante",
        data_partida: "14/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 19,
          empates_fora_casa: 4,
          total_jogos: 46,
          gols_casa: 40,
          jogos_fora_casa: 23,
          vitorias_casa: 11,
          derrotas_casa: 6,
          total_pontos: 46,
          empates_casa: 6,
          pontos_fora_casa: 7,
          total_gols_sofridos: 92,
          total_vitorias: 12,
          vitorias_fora_casa: 1,
          total_derrotas: 24,
          pontos_casa: 39,
          derrotas_fora_casa: 18,
          total_gols_marcados: 59,
          jogos_casa: 23,
          total_empates: 10,
        },
        placar_visitante: 7,
        hora_partida: "16h00",
        mandante: "Bahia",
        placar_mandante: 0,
        estadio: "Fonte Nova",
        pontuacao_geral_visitante: {
          gols_fora_casa: 41,
          empates_fora_casa: 2,
          total_jogos: 46,
          gols_casa: 61,
          jogos_fora_casa: 23,
          vitorias_casa: 17,
          derrotas_casa: 1,
          total_pontos: 100,
          empates_casa: 5,
          pontos_fora_casa: 44,
          total_gols_sofridos: 47,
          total_vitorias: 31,
          vitorias_fora_casa: 14,
          total_derrotas: 8,
          pontos_casa: 56,
          derrotas_fora_casa: 7,
          total_gols_marcados: 102,
          jogos_casa: 23,
          total_empates: 7,
        },
      },
      {
        visitante: "Juventude",
        resultado: "vitoria_mandante",
        data_partida: "14/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 16,
          empates_fora_casa: 4,
          total_jogos: 46,
          gols_casa: 36,
          jogos_fora_casa: 23,
          vitorias_casa: 11,
          derrotas_casa: 5,
          total_pontos: 50,
          empates_casa: 7,
          pontos_fora_casa: 10,
          total_gols_sofridos: 77,
          total_vitorias: 13,
          vitorias_fora_casa: 2,
          total_derrotas: 22,
          pontos_casa: 40,
          derrotas_fora_casa: 17,
          total_gols_marcados: 52,
          jogos_casa: 23,
          total_empates: 11,
        },
        placar_visitante: 0,
        hora_partida: "16h00",
        mandante: "Fluminense",
        placar_mandante: 1,
        estadio: "Maracanã",
        pontuacao_geral_visitante: {
          gols_fora_casa: 19,
          empates_fora_casa: 4,
          total_jogos: 46,
          gols_casa: 36,
          jogos_fora_casa: 23,
          vitorias_casa: 9,
          derrotas_casa: 4,
          total_pontos: 50,
          empates_casa: 10,
          pontos_fora_casa: 13,
          total_gols_sofridos: 70,
          total_vitorias: 12,
          vitorias_fora_casa: 3,
          total_derrotas: 20,
          pontos_casa: 37,
          derrotas_fora_casa: 16,
          total_gols_marcados: 55,
          jogos_casa: 23,
          total_empates: 14,
        },
      },
      {
        visitante: "Atlético pr",
        resultado: "empate",
        data_partida: "14/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 21,
          empates_fora_casa: 5,
          total_jogos: 46,
          gols_casa: 53,
          jogos_fora_casa: 23,
          vitorias_casa: 13,
          derrotas_casa: 3,
          total_pontos: 57,
          empates_casa: 7,
          pontos_fora_casa: 11,
          total_gols_sofridos: 77,
          total_vitorias: 15,
          vitorias_fora_casa: 2,
          total_derrotas: 19,
          pontos_casa: 46,
          derrotas_fora_casa: 16,
          total_gols_marcados: 74,
          jogos_casa: 23,
          total_empates: 12,
        },
        placar_visitante: 2,
        hora_partida: "16h00",
        mandante: "Paysandu",
        placar_mandante: 2,
        estadio: "Mangueirão",
        pontuacao_geral_visitante: {
          gols_fora_casa: 22,
          empates_fora_casa: 6,
          total_jogos: 46,
          gols_casa: 44,
          jogos_fora_casa: 23,
          vitorias_casa: 14,
          derrotas_casa: 5,
          total_pontos: 61,
          empates_casa: 4,
          pontos_fora_casa: 15,
          total_gols_sofridos: 72,
          total_vitorias: 17,
          vitorias_fora_casa: 3,
          total_derrotas: 19,
          pontos_casa: 46,
          derrotas_fora_casa: 14,
          total_gols_marcados: 66,
          jogos_casa: 23,
          total_empates: 10,
        },
      },
      {
        visitante: "Santos",
        resultado: "empate",
        data_partida: "14/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 25,
          empates_fora_casa: 8,
          total_jogos: 46,
          gols_casa: 32,
          jogos_fora_casa: 23,
          vitorias_casa: 11,
          derrotas_casa: 5,
          total_pontos: 54,
          empates_casa: 7,
          pontos_fora_casa: 14,
          total_gols_sofridos: 69,
          total_vitorias: 13,
          vitorias_fora_casa: 2,
          total_derrotas: 18,
          pontos_casa: 40,
          derrotas_fora_casa: 13,
          total_gols_marcados: 57,
          jogos_casa: 23,
          total_empates: 15,
        },
        placar_visitante: 1,
        hora_partida: "18h00",
        mandante: "Vasco",
        placar_mandante: 1,
        estadio: "São Januário",
        pontuacao_geral_visitante: {
          gols_fora_casa: 38,
          empates_fora_casa: 6,
          total_jogos: 46,
          gols_casa: 55,
          jogos_fora_casa: 23,
          vitorias_casa: 15,
          derrotas_casa: 2,
          total_pontos: 87,
          empates_casa: 6,
          pontos_fora_casa: 36,
          total_gols_sofridos: 60,
          total_vitorias: 25,
          vitorias_fora_casa: 10,
          total_derrotas: 9,
          pontos_casa: 51,
          derrotas_fora_casa: 7,
          total_gols_marcados: 93,
          jogos_casa: 23,
          total_empates: 12,
        },
      },
      {
        visitante: "Flamengo",
        resultado: "derrota_mandante",
        data_partida: "14/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 39,
          empates_fora_casa: 7,
          total_jogos: 46,
          gols_casa: 42,
          jogos_fora_casa: 23,
          vitorias_casa: 13,
          derrotas_casa: 5,
          total_pontos: 78,
          empates_casa: 5,
          pontos_fora_casa: 34,
          total_gols_sofridos: 67,
          total_vitorias: 22,
          vitorias_fora_casa: 9,
          total_derrotas: 12,
          pontos_casa: 44,
          derrotas_fora_casa: 7,
          total_gols_marcados: 81,
          jogos_casa: 23,
          total_empates: 12,
        },
        placar_visitante: 3,
        hora_partida: "18h00",
        mandante: "São paulo",
        placar_mandante: 1,
        estadio: "Morumbi",
        pontuacao_geral_visitante: {
          gols_fora_casa: 28,
          empates_fora_casa: 7,
          total_jogos: 46,
          gols_casa: 38,
          jogos_fora_casa: 23,
          vitorias_casa: 14,
          derrotas_casa: 4,
          total_pontos: 66,
          empates_casa: 5,
          pontos_fora_casa: 19,
          total_gols_sofridos: 73,
          total_vitorias: 18,
          vitorias_fora_casa: 4,
          total_derrotas: 16,
          pontos_casa: 47,
          derrotas_fora_casa: 12,
          total_gols_marcados: 66,
          jogos_casa: 23,
          total_empates: 12,
        },
      },
    ],
    numero: 46,
  },
  {
    partidas: [
      {
        visitante: "Vitória",
        resultado: "vitoria_mandante",
        data_partida: "13/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 30,
          empates_fora_casa: 5,
          total_jogos: 46,
          gols_casa: 55,
          jogos_fora_casa: 23,
          vitorias_casa: 13,
          derrotas_casa: 4,
          total_pontos: 65,
          empates_casa: 6,
          pontos_fora_casa: 20,
          total_gols_sofridos: 75,
          total_vitorias: 18,
          vitorias_fora_casa: 5,
          total_derrotas: 17,
          pontos_casa: 45,
          derrotas_fora_casa: 13,
          total_gols_marcados: 85,
          jogos_casa: 23,
          total_empates: 11,
        },
        placar_visitante: 0,
        hora_partida: "16h00",
        mandante: "Paraná",
        placar_mandante: 2,
        estadio: "Pinheirão",
        pontuacao_geral_visitante: {
          gols_fora_casa: 20,
          empates_fora_casa: 6,
          total_jogos: 46,
          gols_casa: 30,
          jogos_fora_casa: 23,
          vitorias_casa: 11,
          derrotas_casa: 7,
          total_pontos: 56,
          empates_casa: 5,
          pontos_fora_casa: 18,
          total_gols_sofridos: 64,
          total_vitorias: 15,
          vitorias_fora_casa: 4,
          total_derrotas: 20,
          pontos_casa: 38,
          derrotas_fora_casa: 13,
          total_gols_marcados: 50,
          jogos_casa: 23,
          total_empates: 11,
        },
      },
      {
        visitante: "Criciúma",
        resultado: "vitoria_mandante",
        data_partida: "13/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 30,
          empates_fora_casa: 5,
          total_jogos: 46,
          gols_casa: 37,
          jogos_fora_casa: 23,
          vitorias_casa: 14,
          derrotas_casa: 4,
          total_pontos: 73,
          empates_casa: 5,
          pontos_fora_casa: 26,
          total_gols_sofridos: 58,
          total_vitorias: 21,
          vitorias_fora_casa: 7,
          total_derrotas: 15,
          pontos_casa: 47,
          derrotas_fora_casa: 11,
          total_gols_marcados: 67,
          jogos_casa: 23,
          total_empates: 10,
        },
        placar_visitante: 0,
        hora_partida: "16h00",
        mandante: "Coritiba",
        placar_mandante: 2,
        estadio: "Couto Pereira",
        pontuacao_geral_visitante: {
          gols_fora_casa: 21,
          empates_fora_casa: 6,
          total_jogos: 46,
          gols_casa: 36,
          jogos_fora_casa: 23,
          vitorias_casa: 14,
          derrotas_casa: 6,
          total_pontos: 60,
          empates_casa: 3,
          pontos_fora_casa: 15,
          total_gols_sofridos: 68,
          total_vitorias: 17,
          vitorias_fora_casa: 3,
          total_derrotas: 20,
          pontos_casa: 45,
          derrotas_fora_casa: 14,
          total_gols_marcados: 57,
          jogos_casa: 23,
          total_empates: 9,
        },
      },
      {
        visitante: "Goiás",
        resultado: "vitoria_mandante",
        data_partida: "13/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 36,
          empates_fora_casa: 10,
          total_jogos: 46,
          gols_casa: 40,
          jogos_fora_casa: 23,
          vitorias_casa: 13,
          derrotas_casa: 5,
          total_pontos: 72,
          empates_casa: 5,
          pontos_fora_casa: 28,
          total_gols_sofridos: 62,
          total_vitorias: 19,
          vitorias_fora_casa: 6,
          total_derrotas: 12,
          pontos_casa: 44,
          derrotas_fora_casa: 7,
          total_gols_marcados: 76,
          jogos_casa: 23,
          total_empates: 15,
        },
        placar_visitante: 2,
        hora_partida: "16h00",
        mandante: "Atlético mg",
        placar_mandante: 3,
        estadio: "Ipatingão",
        pontuacao_geral_visitante: {
          gols_fora_casa: 31,
          empates_fora_casa: 4,
          total_jogos: 46,
          gols_casa: 47,
          jogos_fora_casa: 23,
          vitorias_casa: 12,
          derrotas_casa: 4,
          total_pontos: 65,
          empates_casa: 7,
          pontos_fora_casa: 22,
          total_gols_sofridos: 63,
          total_vitorias: 18,
          vitorias_fora_casa: 6,
          total_derrotas: 17,
          pontos_casa: 43,
          derrotas_fora_casa: 13,
          total_gols_marcados: 78,
          jogos_casa: 23,
          total_empates: 11,
        },
      },
      {
        visitante: "Guarani",
        resultado: "vitoria_mandante",
        data_partida: "13/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 21,
          empates_fora_casa: 6,
          total_jogos: 46,
          gols_casa: 41,
          jogos_fora_casa: 23,
          vitorias_casa: 11,
          derrotas_casa: 4,
          total_pontos: 65,
          empates_casa: 8,
          pontos_fora_casa: 24,
          total_gols_sofridos: 54,
          total_vitorias: 17,
          vitorias_fora_casa: 6,
          total_derrotas: 15,
          pontos_casa: 41,
          derrotas_fora_casa: 11,
          total_gols_marcados: 62,
          jogos_casa: 23,
          total_empates: 14,
        },
        placar_visitante: 0,
        hora_partida: "16h00",
        mandante: "Figueirense",
        placar_mandante: 2,
        estadio: "Orlando Scarpelli",
        pontuacao_geral_visitante: {
          gols_fora_casa: 20,
          empates_fora_casa: 7,
          total_jogos: 46,
          gols_casa: 44,
          jogos_fora_casa: 23,
          vitorias_casa: 15,
          derrotas_casa: 5,
          total_pontos: 61,
          empates_casa: 3,
          pontos_fora_casa: 13,
          total_gols_sofridos: 72,
          total_vitorias: 17,
          vitorias_fora_casa: 2,
          total_derrotas: 19,
          pontos_casa: 48,
          derrotas_fora_casa: 14,
          total_gols_marcados: 64,
          jogos_casa: 23,
          total_empates: 10,
        },
      },
      {
        visitante: "Internacional",
        resultado: "vitoria_mandante",
        data_partida: "13/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 15,
          empates_fora_casa: 9,
          total_jogos: 46,
          gols_casa: 38,
          jogos_fora_casa: 23,
          vitorias_casa: 15,
          derrotas_casa: 3,
          total_pontos: 71,
          empates_casa: 5,
          pontos_fora_casa: 21,
          total_gols_sofridos: 37,
          total_vitorias: 19,
          vitorias_fora_casa: 4,
          total_derrotas: 13,
          pontos_casa: 50,
          derrotas_fora_casa: 10,
          total_gols_marcados: 53,
          jogos_casa: 23,
          total_empates: 14,
        },
        placar_visitante: 0,
        hora_partida: "16h00",
        mandante: "São caetano",
        placar_mandante: 5,
        estadio: "Anacleto Campanella",
        pontuacao_geral_visitante: {
          gols_fora_casa: 27,
          empates_fora_casa: 3,
          total_jogos: 46,
          gols_casa: 32,
          jogos_fora_casa: 23,
          vitorias_casa: 13,
          derrotas_casa: 3,
          total_pontos: 70,
          empates_casa: 7,
          pontos_fora_casa: 24,
          total_gols_sofridos: 57,
          total_vitorias: 20,
          vitorias_fora_casa: 7,
          total_derrotas: 16,
          pontos_casa: 46,
          derrotas_fora_casa: 13,
          total_gols_marcados: 59,
          jogos_casa: 23,
          total_empates: 10,
        },
      },
      {
        visitante: "Corinthians",
        resultado: "vitoria_mandante",
        data_partida: "14/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 21,
          empates_fora_casa: 5,
          total_jogos: 46,
          gols_casa: 33,
          jogos_fora_casa: 23,
          vitorias_casa: 10,
          derrotas_casa: 7,
          total_pontos: 50,
          empates_casa: 6,
          pontos_fora_casa: 14,
          total_gols_sofridos: 68,
          total_vitorias: 13,
          vitorias_fora_casa: 3,
          total_derrotas: 22,
          pontos_casa: 36,
          derrotas_fora_casa: 15,
          total_gols_marcados: 54,
          jogos_casa: 23,
          total_empates: 11,
        },
        placar_visitante: 0,
        hora_partida: "16h00",
        mandante: "Grêmio",
        placar_mandante: 3,
        estadio: "Olímpico",
        pontuacao_geral_visitante: {
          gols_fora_casa: 25,
          empates_fora_casa: 8,
          total_jogos: 46,
          gols_casa: 36,
          jogos_fora_casa: 23,
          vitorias_casa: 11,
          derrotas_casa: 8,
          total_pontos: 57,
          empates_casa: 4,
          pontos_fora_casa: 20,
          total_gols_sofridos: 63,
          total_vitorias: 15,
          vitorias_fora_casa: 4,
          total_derrotas: 19,
          pontos_casa: 37,
          derrotas_fora_casa: 11,
          total_gols_marcados: 61,
          jogos_casa: 23,
          total_empates: 12,
        },
      },
      {
        visitante: "Fortaleza",
        resultado: "vitoria_mandante",
        data_partida: "14/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 26,
          empates_fora_casa: 8,
          total_jogos: 46,
          gols_casa: 37,
          jogos_fora_casa: 23,
          vitorias_casa: 7,
          derrotas_casa: 6,
          total_pontos: 51,
          empates_casa: 10,
          pontos_fora_casa: 20,
          total_gols_sofridos: 73,
          total_vitorias: 11,
          vitorias_fora_casa: 4,
          total_derrotas: 17,
          pontos_casa: 31,
          derrotas_fora_casa: 11,
          total_gols_marcados: 63,
          jogos_casa: 23,
          total_empates: 18,
        },
        placar_visitante: 0,
        hora_partida: "16h00",
        mandante: "Ponte preta",
        placar_mandante: 2,
        estadio: "Moisés Lucarelli",
        pontuacao_geral_visitante: {
          gols_fora_casa: 19,
          empates_fora_casa: 7,
          total_jogos: 46,
          gols_casa: 39,
          jogos_fora_casa: 23,
          vitorias_casa: 10,
          derrotas_casa: 7,
          total_pontos: 49,
          empates_casa: 6,
          pontos_fora_casa: 13,
          total_gols_sofridos: 74,
          total_vitorias: 12,
          vitorias_fora_casa: 2,
          total_derrotas: 21,
          pontos_casa: 36,
          derrotas_fora_casa: 14,
          total_gols_marcados: 58,
          jogos_casa: 23,
          total_empates: 13,
        },
      },
      {
        visitante: "Cruzeiro",
        resultado: "derrota_mandante",
        data_partida: "14/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 19,
          empates_fora_casa: 4,
          total_jogos: 46,
          gols_casa: 40,
          jogos_fora_casa: 23,
          vitorias_casa: 11,
          derrotas_casa: 6,
          total_pontos: 46,
          empates_casa: 6,
          pontos_fora_casa: 7,
          total_gols_sofridos: 92,
          total_vitorias: 12,
          vitorias_fora_casa: 1,
          total_derrotas: 24,
          pontos_casa: 39,
          derrotas_fora_casa: 18,
          total_gols_marcados: 59,
          jogos_casa: 23,
          total_empates: 10,
        },
        placar_visitante: 7,
        hora_partida: "16h00",
        mandante: "Bahia",
        placar_mandante: 0,
        estadio: "Fonte Nova",
        pontuacao_geral_visitante: {
          gols_fora_casa: 41,
          empates_fora_casa: 2,
          total_jogos: 46,
          gols_casa: 61,
          jogos_fora_casa: 23,
          vitorias_casa: 17,
          derrotas_casa: 1,
          total_pontos: 100,
          empates_casa: 5,
          pontos_fora_casa: 44,
          total_gols_sofridos: 47,
          total_vitorias: 31,
          vitorias_fora_casa: 14,
          total_derrotas: 8,
          pontos_casa: 56,
          derrotas_fora_casa: 7,
          total_gols_marcados: 102,
          jogos_casa: 23,
          total_empates: 7,
        },
      },
      {
        visitante: "Juventude",
        resultado: "vitoria_mandante",
        data_partida: "14/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 16,
          empates_fora_casa: 4,
          total_jogos: 46,
          gols_casa: 36,
          jogos_fora_casa: 23,
          vitorias_casa: 11,
          derrotas_casa: 5,
          total_pontos: 50,
          empates_casa: 7,
          pontos_fora_casa: 10,
          total_gols_sofridos: 77,
          total_vitorias: 13,
          vitorias_fora_casa: 2,
          total_derrotas: 22,
          pontos_casa: 40,
          derrotas_fora_casa: 17,
          total_gols_marcados: 52,
          jogos_casa: 23,
          total_empates: 11,
        },
        placar_visitante: 0,
        hora_partida: "16h00",
        mandante: "Fluminense",
        placar_mandante: 1,
        estadio: "Maracanã",
        pontuacao_geral_visitante: {
          gols_fora_casa: 19,
          empates_fora_casa: 4,
          total_jogos: 46,
          gols_casa: 36,
          jogos_fora_casa: 23,
          vitorias_casa: 9,
          derrotas_casa: 4,
          total_pontos: 50,
          empates_casa: 10,
          pontos_fora_casa: 13,
          total_gols_sofridos: 70,
          total_vitorias: 12,
          vitorias_fora_casa: 3,
          total_derrotas: 20,
          pontos_casa: 37,
          derrotas_fora_casa: 16,
          total_gols_marcados: 55,
          jogos_casa: 23,
          total_empates: 14,
        },
      },
      {
        visitante: "Atlético pr",
        resultado: "empate",
        data_partida: "14/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 21,
          empates_fora_casa: 5,
          total_jogos: 46,
          gols_casa: 53,
          jogos_fora_casa: 23,
          vitorias_casa: 13,
          derrotas_casa: 3,
          total_pontos: 57,
          empates_casa: 7,
          pontos_fora_casa: 11,
          total_gols_sofridos: 77,
          total_vitorias: 15,
          vitorias_fora_casa: 2,
          total_derrotas: 19,
          pontos_casa: 46,
          derrotas_fora_casa: 16,
          total_gols_marcados: 74,
          jogos_casa: 23,
          total_empates: 12,
        },
        placar_visitante: 2,
        hora_partida: "16h00",
        mandante: "Paysandu",
        placar_mandante: 2,
        estadio: "Mangueirão",
        pontuacao_geral_visitante: {
          gols_fora_casa: 22,
          empates_fora_casa: 6,
          total_jogos: 46,
          gols_casa: 44,
          jogos_fora_casa: 23,
          vitorias_casa: 14,
          derrotas_casa: 5,
          total_pontos: 61,
          empates_casa: 4,
          pontos_fora_casa: 15,
          total_gols_sofridos: 72,
          total_vitorias: 17,
          vitorias_fora_casa: 3,
          total_derrotas: 19,
          pontos_casa: 46,
          derrotas_fora_casa: 14,
          total_gols_marcados: 66,
          jogos_casa: 23,
          total_empates: 10,
        },
      },
      {
        visitante: "Santos",
        resultado: "empate",
        data_partida: "14/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 25,
          empates_fora_casa: 8,
          total_jogos: 46,
          gols_casa: 32,
          jogos_fora_casa: 23,
          vitorias_casa: 11,
          derrotas_casa: 5,
          total_pontos: 54,
          empates_casa: 7,
          pontos_fora_casa: 14,
          total_gols_sofridos: 69,
          total_vitorias: 13,
          vitorias_fora_casa: 2,
          total_derrotas: 18,
          pontos_casa: 40,
          derrotas_fora_casa: 13,
          total_gols_marcados: 57,
          jogos_casa: 23,
          total_empates: 15,
        },
        placar_visitante: 1,
        hora_partida: "18h00",
        mandante: "Vasco",
        placar_mandante: 1,
        estadio: "São Januário",
        pontuacao_geral_visitante: {
          gols_fora_casa: 38,
          empates_fora_casa: 6,
          total_jogos: 46,
          gols_casa: 55,
          jogos_fora_casa: 23,
          vitorias_casa: 15,
          derrotas_casa: 2,
          total_pontos: 87,
          empates_casa: 6,
          pontos_fora_casa: 36,
          total_gols_sofridos: 60,
          total_vitorias: 25,
          vitorias_fora_casa: 10,
          total_derrotas: 9,
          pontos_casa: 51,
          derrotas_fora_casa: 7,
          total_gols_marcados: 93,
          jogos_casa: 23,
          total_empates: 12,
        },
      },
      {
        visitante: "Flamengo",
        resultado: "derrota_mandante",
        data_partida: "14/12/2003",
        pontuacao_geral_mandante: {
          gols_fora_casa: 39,
          empates_fora_casa: 7,
          total_jogos: 46,
          gols_casa: 42,
          jogos_fora_casa: 23,
          vitorias_casa: 13,
          derrotas_casa: 5,
          total_pontos: 78,
          empates_casa: 5,
          pontos_fora_casa: 34,
          total_gols_sofridos: 67,
          total_vitorias: 22,
          vitorias_fora_casa: 9,
          total_derrotas: 12,
          pontos_casa: 44,
          derrotas_fora_casa: 7,
          total_gols_marcados: 81,
          jogos_casa: 23,
          total_empates: 12,
        },
        placar_visitante: 3,
        hora_partida: "18h00",
        mandante: "São paulo",
        placar_mandante: 1,
        estadio: "Morumbi",
        pontuacao_geral_visitante: {
          gols_fora_casa: 28,
          empates_fora_casa: 7,
          total_jogos: 46,
          gols_casa: 38,
          jogos_fora_casa: 23,
          vitorias_casa: 14,
          derrotas_casa: 4,
          total_pontos: 66,
          empates_casa: 5,
          pontos_fora_casa: 19,
          total_gols_sofridos: 73,
          total_vitorias: 18,
          vitorias_fora_casa: 4,
          total_derrotas: 16,
          pontos_casa: 47,
          derrotas_fora_casa: 12,
          total_gols_marcados: 66,
          jogos_casa: 23,
          total_empates: 12,
        },
      },
    ],
    numero: 46,
  },
];
